version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    working_dir: /app
    command: python main.py
    restart: on-failure

  hadoop-pig:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-pig
    ports:
      - "50070:50070"
    volumes:
      - ./app:/data
    tty: true
