version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    working_dir: /app
    command: python main.py

  hadoop:
    image: gettyimages/hadoop-pig:2.7.1
    container_name: hadoop
    ports:
      - "9870:9870"  # Hadoop Namenode UI
      - "9000:9000"  # HDFS Namenode puerto
    volumes:
      - ./app:/data
    command: /bin/bash -c "while true; do sleep 1000; done"