version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    working_dir: /app
    command: python main.py

  hadoop:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop
    ports:
      - "9870:9870"  # Web UI de HDFS
      - "9000:9000"
    environment:
      - CLUSTER_NAME=waze-cluster
    volumes:
      - ./data:/data  # Asegúrate de poner aquí el CSV que generaste
    command: ["/bin/bash", "-c", "service ssh start && /entrypoint.sh"]
