version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data_eventos_waze:/data/db
    restart: unless-stopped
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    working_dir: /app
    command: python main.py
    environment:
      - MONGO_URI=mongodb://mongo:27017