FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

#dependencias básicas
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      openjdk-8-jdk-headless \
      ssh \
      rsync \
      wget \
      vim \
      ca-certificates \
      procps \
    && rm -rf /var/lib/apt/lists/*

#usuario hadoop 
RUN useradd -m -s /bin/bash hadoop && \
    mkdir -p /home/hadoop/.ssh && \
    ssh-keygen -t rsa -P "" -f /home/hadoop/.ssh/id_rsa && \
    cat /home/hadoop/.ssh/id_rsa.pub >> /home/hadoop/.ssh/authorized_keys && \
    chown -R hadoop:hadoop /home/hadoop

RUN echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> /home/hadoop/.bashrc

#variables de entorno Java
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

#Hadoop 3.3.1
ENV HADOOP_VERSION=3.3.1
ENV HADOOP_HOME=/opt/hadoop
ENV HADOOP_DOWNLOAD_URL=https://downloads.apache.org/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz

RUN wget -qO- $HADOOP_DOWNLOAD_URL \
    | tar -xz -C /opt/ && \
    mv /opt/hadoop-${HADOOP_VERSION} /opt/hadoop && \
    chown -R hadoop:hadoop /opt/hadoop

#variables de entorno Hadoop
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
ENV HADOOP_COMMON_HOME=$HADOOP_HOME
ENV HADOOP_HDFS_HOME=$HADOOP_HOME
ENV HADOOP_MAPRED_HOME=$HADOOP_HOME
ENV HADOOP_YARN_HOME=$HADOOP_HOME
ENV YARN_CONF_DIR=$HADOOP_HOME/etc/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

#Pig
ENV PIG_VERSION=0.17.0
ENV PIG_HOME=/opt/pig
ENV PIG_DOWNLOAD_URL=https://downloads.apache.org/pig/pig-${PIG_VERSION}/pig-${PIG_VERSION}.tar.gz

RUN wget -qO- $PIG_DOWNLOAD_URL \
    | tar -xz -C /opt/ && \
    mv /opt/pig-${PIG_VERSION} /opt/pig && \
    chown -R hadoop:hadoop /opt/pig

ENV PATH=$PATH:$PIG_HOME/bin

COPY config/ $HADOOP_CONF_DIR/

#permisos
COPY init-hadoop.sh /init-hadoop.sh
RUN chmod +x /init-hadoop.sh && chown hadoop:hadoop /init-hadoop.sh

#HDFS
RUN mkdir -p /hadoop/dfs/name && chown -R hadoop:hadoop /hadoop

#usuario hadoop
USER hadoop
WORKDIR /home/hadoop

CMD ["/init-hadoop.sh"]
